app: # 系统全局配置文件
  db: # 数据库配置(当前只支持mysql)
    mysql: # mysql
      host: 192.168.52.153
      port: '3306'
      dbname: apikiller
      username: root
      password: '123456'
  origin: # 数据源配置
    realTime: # 实时监听数据源配置
      address: 127.0.0.1
      port: '8080' # 监听端口
  module: # 核心模块配置
    authorizedDetector: # 未授权&越权检测模块配置
      option: 1 # 模块开关
      authHeader: cookie # 探测系统使用的鉴权头，例如cookie、X-Signature或自定义鉴权头
      roles: # 不同权限的鉴权头value（目前只处理第一个角色）
        - "ASP.NET_SessionId=1tmfsnlwrkdf1fbcokn1ehrd; path=/; HttpOnly; SameSite=Lax"
      judgement: # 判断引擎配置
        blackStatusCodes: # 鉴权失败响应码
          - 403
          - 401
        blackKeywords: # 鉴权失败响应关键字
          - forbidden
          - error
    CSRFDetector: # csrf检测模块
      option: 1 # 模块开关
      csrfTokenPattern: csrf # token对应的参数名或者请求头
      csrfInvalidPattern: # csrf鉴权失败返回的标识
        - invalid
        - csrf
    openRedirectDetector: # openRedirect检测
      option: 1
      rawQueryParams:
        - url
        - redirect
        - uri
        - redirection
        - next
        - returnto
        - return_to
        - origin
        - callback
        - authorize_callback
        - target
        - link
      failFlag:
        - error
        - fail
    DoSDetector: # dos检测模块
      option: 1
      sizeParam: # 资源查询大小控制参数
        - size
        - Size
      rateLimit:
        failFlag: # 存在频控的标识
          - exceed
          - captcha
          - too many
          - rate limit
          - Maximum login
    SSRFDetector:
      option: 1
  filter: # 过滤器配置
    httpFilter: # http过滤器配置：目前只支持根据指定的host，对其进行检测，如果未设置，则默认对所有流量进行检测
      host:
        -
    staticFileFilter: # 静态文件过滤器：对获取静态资源的流量不做处理
      ext:
        - js
        - gif
        - jpg
        - png
        - css
        - jpeg
        - xml
        - img
        - svg
        - ico
  notifier: # 通知方式配置
    Lark: # Lark飞书（支持token检验）
      webhookUrl: 'https://open.feishu.cn/open-apis/bot/v2/hook/a814553d-3fc0-4c5b-8e98-694830cc3121'
      secret: ''
    Dingding: # 钉钉
      webhookUrl: ''
  other: # 其他配置
    reverseTarget: 127.0.0.1 # 反连平台目标
  web: # web运营平台配置
    ipaddr: 127.0.0.1
    port: '80'
